#10 add option to popup menu
henices/Chrome-proxy-helper pull request #11
Opened 2018-02-01 04:40 UTC by vanduc1102

#### What does this PR do?
add option to popup menu

#### screenshots?
![image](https://user-images.githubusercontent.com/3014017/35661426-a6c8d990-0744-11e8-8e85-f90c73aca486.png)

2018-02-01 05:44 UTC, henices commented
Thank you for your contribution, but did you notice that we have a shortcut  Alt +O to go to the option page directly.

2018-02-02 09:57 UTC, vanduc1102 commented
hi @henices , i haven't noticed the option.
but Alt + O may conflicts with other hotkey.

2023-05-31 11:40 UTC, pepijnmm requested changes
You can also right click on the extention and then click on options to get the option screen.
But I indeed think that this pr should be included because most people are used to finding the option menu by just left clicking it.

2023-05-31 11:40 UTC, pepijnmm commented on popup.html
> +                    <span id="option" class="text" data-i18n-content="direct_proxy">OPTIONS</span>
the data-il18n is wrong. I would expect "option_page"

2023-05-31 11:40 UTC, pepijnmm commented on _locales/zh_CN/messages.json
> +    "option-page" : {
for consistency I would use a _ instead of a -

2025-12-23 10:06 UTC, closed without merging